export const RESTAURANTS = [
	{
		name: "Restaurant 1",
		description: "Make Yourself at home!",
		key: 1,
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xFileName: "candles.png",
				xPrice: 1.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Powerbank",
				xFileName: "powerbank.png",
				xPrice: 4.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Fresh Flowers Mix",
				xFileName: "freshFlowersMix.png",
				xPrice: 14.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Baby Chair",
				xFileName: "babyChair.png",
				xPrice: 0,
				xAvailability: true,
				xPicked: false,
			},
		],
	},
	{
		name: "Restaurant 2",
		description: "Make Yourself at home!",
		key: 2,
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xFileName: "candles.png",
				xPrice: 1.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Powerbank",
				xFileName: "powerbank.png",
				xPrice: 4.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Fresh Flowers Mix",
				xFileName: "freshFlowersMix.png",
				xPrice: 14.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Baby Chair",
				xFileName: "babyChair.png",
				xPrice: 0,
				xAvailability: true,
				xPicked: false,
			},
		],
	},
	{
		name: "Restaurant 3",
		description: "Make Yourself at home!",
		key: 3,
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xFileName: "candles.png",
				xPrice: 1.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Powerbank",
				xFileName: "powerbank.png",
				xPrice: 4.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Fresh Flowers Mix",
				xFileName: "freshFlowersMix.png",
				xPrice: 14.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Baby Chair",
				xFileName: "babyChair.png",
				xPrice: 0,
				xAvailability: true,
				xPicked: false,
			},
		],
	},
	{
		name: "Restaurant 4",
		description: "Make Yourself at home!",
		key: 4,
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xFileName: "candles.png",
				xPrice: 1.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Powerbank",
				xFileName: "powerbank.png",
				xPrice: 4.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Fresh Flowers Mix",
				xFileName: "freshFlowersMix.png",
				xPrice: 14.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Baby Chair",
				xFileName: "babyChair.png",
				xPrice: 0,
				xAvailability: true,
				xPicked: false,
			},
		],
	},
	{
		name: "Restaurant 5",
		description: "Make Yourself at home!",
		key: 5,
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xFileName: "candles.png",
				xPrice: 1.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Powerbank",
				xFileName: "powerbank.png",
				xPrice: 4.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Fresh Flowers Mix",
				xFileName: "freshFlowersMix.png",
				xPrice: 14.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Baby Chair",
				xFileName: "babyChair.png",
				xPrice: 0,
				xAvailability: true,
				xPicked: false,
			},
		],
	},
	{
		name: "Restaurant 6",
		description: "Make Yourself at home!",
		key: 6,
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xFileName: "candles.png",
				xPrice: 1.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Powerbank",
				xFileName: "powerbank.png",
				xPrice: 4.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Fresh Flowers Mix",
				xFileName: "freshFlowersMix.png",
				xPrice: 14.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Baby Chair",
				xFileName: "babyChair.png",
				xPrice: 0,
				xAvailability: true,
				xPicked: false,
			},
		],
	},
	{
		name: "Restaurant 7",
		description: "Make Yourself at home!",
		key: 7,
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xFileName: "candles.png",
				xPrice: 1.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Powerbank",
				xFileName: "powerbank.png",
				xPrice: 4.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Fresh Flowers Mix",
				xFileName: "freshFlowersMix.png",
				xPrice: 14.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Baby Chair",
				xFileName: "babyChair.png",
				xPrice: 0,
				xAvailability: true,
				xPicked: false,
			},
		],
	},
	{
		name: "Restaurant 8",
		description: "Make Yourself at home!",
		key: 8,
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xFileName: "candles.png",
				xPrice: 1.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Powerbank",
				xFileName: "powerbank.png",
				xPrice: 4.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Fresh Flowers Mix",
				xFileName: "freshFlowersMix.png",
				xPrice: 14.99,
				xAvailability: true,
				xPicked: false,
			},
			{
				xName: "Baby Chair",
				xFileName: "babyChair.png",
				xPrice: 0,
				xAvailability: true,
				xPicked: false,
			},
		],
	},
];
