export const RESTAURANTS = [
	{
		name: "Restaurant 1",
		description: "Make Yourself at home!",
		key: 1,
		imageUri: require("../assets/imgs/restaurant1.jpg"),
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xImage: null,
				xPrice: 0.99,
				xAvailability: true,
			},
			{
				xName: "Powerbank",
				xImage: null,
				xPrice: 4.99,
				xAvailability: true,
			},
			{
				xName: "Fresh Flowers Mix",
				xImage: null,
				xPrice: 14.99,
				xAvailability: true,
			},
			{
				xName: "Baby Chair",
				xImage: null,
				xPrice: 0,
				xAvailability: true,
			},
		],
	},
	{
		name: "Restaurant 2",
		description: "Make Yourself at home!",
		key: 2,
		imageUri: require("../assets/imgs/restaurant2.jpg"),
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xImage: null,
				xPrice: 0.99,
				xAvailability: true,
			},
			{
				xName: "Powerbank",
				xImage: null,
				xPrice: 4.99,
				xAvailability: true,
			},
			{
				xName: "Fresh Flowers Mix",
				xImage: null,
				xPrice: 14.99,
				xAvailability: true,
			},
			{
				xName: "Baby Chair",
				xImage: null,
				xPrice: 0,
				xAvailability: true,
			},
		],
	},
	{
		name: "Restaurant 3",
		description: "Make Yourself at home!",
		key: 3,
		imageUri: require("../assets/imgs/restaurant3.jpg"),
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xImage: null,
				xPrice: 0.99,
				xAvailability: true,
			},
			{
				xName: "Powerbank",
				xImage: null,
				xPrice: 4.99,
				xAvailability: true,
			},
			{
				xName: "Fresh Flowers Mix",
				xImage: null,
				xPrice: 14.99,
				xAvailability: true,
			},
			{
				xName: "Baby Chair",
				xImage: null,
				xPrice: 0,
				xAvailability: true,
			},
		],
	},
	{
		name: "Restaurant 4",
		description: "Make Yourself at home!",
		key: 4,
		imageUri: require("../assets/imgs/restaurant4.jpg"),
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xImage: null,
				xPrice: 0.99,
				xAvailability: true,
			},
			{
				xName: "Powerbank",
				xImage: null,
				xPrice: 4.99,
				xAvailability: true,
			},
			{
				xName: "Fresh Flowers Mix",
				xImage: null,
				xPrice: 14.99,
				xAvailability: true,
			},
			{
				xName: "Baby Chair",
				xImage: null,
				xPrice: 0,
				xAvailability: true,
			},
		],
	},
	{
		name: "Restaurant 5",
		description: "Make Yourself at home!",
		key: 5,
		imageUri: require("../assets/imgs/restaurant5.jpg"),
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xImage: null,
				xPrice: 0.99,
				xAvailability: true,
			},
			{
				xName: "Powerbank",
				xImage: null,
				xPrice: 4.99,
				xAvailability: true,
			},
			{
				xName: "Fresh Flowers Mix",
				xImage: null,
				xPrice: 14.99,
				xAvailability: true,
			},
			{
				xName: "Baby Chair",
				xImage: null,
				xPrice: 0,
				xAvailability: true,
			},
		],
	},
	{
		name: "Restaurant 6",
		description: "Make Yourself at home!",
		key: 6,
		imageUri: require("../assets/imgs/restaurant6.jpg"),
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xImage: null,
				xPrice: 0.99,
				xAvailability: true,
			},
			{
				xName: "Powerbank",
				xImage: null,
				xPrice: 4.99,
				xAvailability: true,
			},
			{
				xName: "Fresh Flowers Mix",
				xImage: null,
				xPrice: 14.99,
				xAvailability: true,
			},
			{
				xName: "Baby Chair",
				xImage: null,
				xPrice: 0,
				xAvailability: true,
			},
		],
	},
	{
		name: "Restaurant 7",
		description: "Make Yourself at home!",
		key: 7,
		imageUri: require("../assets/imgs/restaurant7.jpg"),
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xImage: null,
				xPrice: 0.99,
				xAvailability: true,
			},
			{
				xName: "Powerbank",
				xImage: null,
				xPrice: 4.99,
				xAvailability: true,
			},
			{
				xName: "Fresh Flowers Mix",
				xImage: null,
				xPrice: 14.99,
				xAvailability: true,
			},
			{
				xName: "Baby Chair",
				xImage: null,
				xPrice: 0,
				xAvailability: true,
			},
		],
	},
	{
		name: "Restaurant 8",
		description: "Make Yourself at home!",
		key: 8,
		imageUri: require("../assets/imgs/restaurant8.jpg"),
		tables: [
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 1,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 2,
				tShape: "Round",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 4,
				tShape: "Square",
				tAvailability: true,
				tPicked: false,
			},
			{
				tSeats: 6,
				tShape: "Rectangle",
				tAvailability: true,
				tPicked: false,
			},
		],
		extras: [
			{
				xName: "Candles",
				xImage: null,
				xPrice: 0.99,
				xAvailability: true,
			},
			{
				xName: "Powerbank",
				xImage: null,
				xPrice: 4.99,
				xAvailability: true,
			},
			{
				xName: "Fresh Flowers Mix",
				xImage: null,
				xPrice: 14.99,
				xAvailability: true,
			},
			{
				xName: "Baby Chair",
				xImage: null,
				xPrice: 0,
				xAvailability: true,
			},
		],
	},
];
